builds:
  - goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "BUcKET {{ .Tag }}"
changelog:
  sort: asc
nfpms:
  - maintainer: Pixel Häußler <pixel+packages@chrissx.de>
    description: An IP echoer.
    homepage: https://github.com/pixelcmtd/bucket
    license: AGPLv3
    formats:
      - deb
      - rpm
